---
- name: apply security patch
  hosts: idm_nodes
  tags: Data protection

  tasks:
    - name: list directory 
      command: ls -ltr

    - name: listening services
      command: netstat -ant | grep LISTEN

    - name: encrypt password
      command: /opt/openidm/cli.sh secureHash openidm-admin
      register: encryptedPwd
      debug: 
        - msg: encryptedPwd
