---
- name: apply security patch
  hosts: idm_nodes
  tags: Data protection

  tasks:
    - name: list directory 
      command: ls -ltr

    - name: listening services
      command: netstat -ant | grep LISTEN

    - name: encrypt password
      shell: |
        /opt/openidm/cli.sh secureHash openidm-admin |
        egrep -v 'Starting|Executing|\-BEGIN|\-END' |
        tr -d '\n' | tr -d ' '
      register: encryptedVal

    - debug:
        msg: "{{ encryptedVal.stdout }}"

    - name: Copy content to file
      copy:
        content: "{{ encryptedVal.stdout }}"
        dest: /tmp/output.txt
        mode: 0400

    - name: Get existing internaluser
      uri:
        url: 'https://localhost:9443/openidm/internal/user/openidm-admin?_prettyPrint=true'
        headers:
          X-OpenIDM-Username: 'openidm-admin'
          X-OpenIDM-Password: 'openidm-admin'
        method: GET 
      register: getUrlOut

     - debug:
         msg: "{{ getUrlOut.stdout }}"
