---
- name: Update IDM credentials 
  hosts: idm_nodes
  tags: idm_data_crypt 
  vars:
    curr_pwd: 'openidm-admin'
    new_pwd: 'openidm-admin'
    temp_output: /tmp/tmpIDM.txt
    final_output: /tmp/tmpIDM.json

  tasks:

    - name: create temporary file
      tempfile:
        state: file
        suffix: temp
      register: tempFile

    debug:
      msg: "{{ tempFile.stdout }}"

    - debug:
        msg: "{{ var1 }} {{ var2 }}"

    - name: Read all tokens 
      shell: |
        echo "current password is {{ curr_pwd }}"

    - name: Get new token 
      shell: echo "new password is {{ new_pwd }}"  

    - name: Encrypt new token 
      shell: |
        /opt/openidm/cli.sh secureHash "{{ new_pwd }}" |
        egrep -v 'Starting|Executing|\-BEGIN|\-END' |
        tr -d '\n' | tr -d ' '
      register: encrypted

    - name: Save encrypted content to file
      copy:
        content: "{{ encrypted.stdout }}"
        dest: "{{ temp_output }}" 
        mode: 0400

    - name: Get internaluser data
      uri:
        url: 'https://localhost:9443/openidm/internal/user/openidm-admin?_prettyPrint=true'
        headers:
          X-OpenIDM-Username: openidm-admin
          X-OpenIDM-Password: "{{ curr_pwd }}"
        method: GET 
      register: getResponse

    - name: Save json response to file
      copy:
        content: "{{ getResponse.json }}"
        dest: "{{ final_output }}" 
        mode: 0600

    - name: Modify the json content 
      lineinfile: 
        dest: "{{ final_output }}" 
        regexp: '(.*)("password".*)("roles".*)'
        line: '\g<1>"password": {{ encrypted.stdout }}, \g<3>' 
        backrefs: true

    - name: Read json content from file
      shell: cat "{{ final_output }}"
      register: jsonString

    - name: Update internaluser record
      uri:
        url: 'https://localhost:9443/openidm/internal/user/openidm-admin?_prettyPrint=true'
        headers:
          X-OpenIDM-Username: 'openidm-admin'
          X-OpenIDM-Password: "{{ curr_pwd }}"
        method: PUT
        body_format: json
        body: "{{ jsonString.stdout }}"
