---
- name: apply security patch
  hosts: idm_nodes
  tags: Data protection

  tasks:
    - name: encrypt password
      command: |
        ls -ltr
        netstat -ant | grep LISTEN
        touch /home/jenkins/done.log
